FROM amazoncorretto:17.0.6-al2

RUN mkdir /app
WORKDIR '/app'

ARG JAR_FILE=build/libs/*-SNAPSHOT.jar
ARG PROFILE
ENV SPRING_PROFILE_ACTIVE=$PROFILE
ARG ENCRYPTOR_PASSWORD
ENV JASRYPT_ENCRYPTOR_PASSWORD=$ENCRYPTOR_PASSWORD
ENV APP_ENCRYPTION_PASSWORD=$ENCRYPTOR_PASSWORD
COPY ${JAR_FILE} app.jar
EXPOSE 8080

CMD java -Dspring.profiles.active=${SPRING_PROFILE_ACTIVE} -Djasrypt.encryptor.password=${JASRYPT_ENCRYPTOR_PASSWORD} -jar app.jar

